### ISSUE TITLE
Create categories

### ISSUE THREAD

**Issue by willikay11** [Aztec-Sytems/neiley#40]
#### Todo

- [x] Create categories with name, slug, weight, active and banner photo
- [ ] Add image resize functionality
- [x] Add a tree that will adequately display the menus
- [x] Limit the menus to 3 levels
