### ISSUE TITLE
Create sliders

### ISSUE THREAD

**Issue by willikay11** [Aztec-Sytems/neiley#47]
#### Todo
- [x] Add module in back end for sliders
   - [x] Image upload field
   - [x] Slider text
   - [x] Button name
   - [x] Button link
- [x] Add database model
- [x] Add validation
- [x] Add Controller
- [x] Edit slider
- [x] Delete slider
- [x] Display 3 sliders on the front end
