### ISSUE TITLE
Create Brands

### ISSUE THREAD

**Issue by willikay11** [Aztec-Sytems/neiley#49]
#### Todo
- [x] Add module in back end for brands
   - [x] Image upload field
   - [x] Brand name
   - [x] Active status
- [x] Add database model
- [x] Add validation
- [x] Add Controller
- [x] Edit brand
- [x] Delete brand
- [x] Display brands on the front end
